# Generated by Django 5.2.7 on 2025-10-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('roll', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='def.jpg', null=True, upload_to='students/imange')),
            ],
        ),
    ]
